#############################################################################
# Makefile for building: untitled
# Generated by qmake (2.01a) (Qt 4.6.2) on: Thu Nov 22 00:45:26 2012
# Project:  untitled.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile untitled.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Mainwindow.cpp \
		criadouro.cpp \
		dispose.cpp \
		mensagem.cpp \
		simulador.cpp \
		distribuicao.cpp \
		central.cpp \
		tempo.cpp \
		release_central.cpp \
		estatisticas.cpp moc_Mainwindow.cpp
OBJECTS       = main.o \
		Mainwindow.o \
		criadouro.o \
		dispose.o \
		mensagem.o \
		simulador.o \
		distribuicao.o \
		central.o \
		tempo.o \
		release_central.o \
		estatisticas.o \
		moc_Mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		untitled.pro
QMAKE_TARGET  = untitled
DESTDIR       = 
TARGET        = untitled

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: untitled.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile untitled.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile untitled.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/untitled1.0.0 || $(MKDIR) .tmp/untitled1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/untitled1.0.0/ && $(COPY_FILE) --parents Mainwindow.h criadouro.h dispose.h evento.h mensagem.h simulador.h distribuicao.h central.h tempo.h release_central.h estatisticas.h .tmp/untitled1.0.0/ && $(COPY_FILE) --parents main.cpp Mainwindow.cpp criadouro.cpp dispose.cpp mensagem.cpp simulador.cpp distribuicao.cpp central.cpp tempo.cpp release_central.cpp estatisticas.cpp .tmp/untitled1.0.0/ && $(COPY_FILE) --parents Mainwindow.ui .tmp/untitled1.0.0/ && (cd `dirname .tmp/untitled1.0.0` && $(TAR) untitled1.0.0.tar untitled1.0.0 && $(COMPRESS) untitled1.0.0.tar) && $(MOVE) `dirname .tmp/untitled1.0.0`/untitled1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/untitled1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Mainwindow.cpp
moc_Mainwindow.cpp: simulador.h \
		tempo.h \
		evento.h \
		central.h \
		mensagem.h \
		Mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Mainwindow.h -o moc_Mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Mainwindow.h
ui_Mainwindow.h: Mainwindow.ui
	/usr/bin/uic-qt4 Mainwindow.ui -o ui_Mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Mainwindow.h \
		simulador.h \
		tempo.h \
		evento.h \
		central.h \
		mensagem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Mainwindow.o: Mainwindow.cpp Mainwindow.h \
		simulador.h \
		tempo.h \
		evento.h \
		central.h \
		mensagem.h \
		ui_Mainwindow.h \
		criadouro.h \
		distribuicao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mainwindow.o Mainwindow.cpp

criadouro.o: criadouro.cpp criadouro.h \
		evento.h \
		tempo.h \
		mensagem.h \
		central.h \
		distribuicao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o criadouro.o criadouro.cpp

dispose.o: dispose.cpp dispose.h \
		evento.h \
		tempo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispose.o dispose.cpp

mensagem.o: mensagem.cpp mensagem.h \
		tempo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mensagem.o mensagem.cpp

simulador.o: simulador.cpp simulador.h \
		tempo.h \
		evento.h \
		central.h \
		mensagem.h \
		dispose.h \
		criadouro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulador.o simulador.cpp

distribuicao.o: distribuicao.cpp distribuicao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o distribuicao.o distribuicao.cpp

central.o: central.cpp central.h \
		tempo.h \
		mensagem.h \
		evento.h \
		distribuicao.h \
		release_central.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o central.o central.cpp

tempo.o: tempo.cpp tempo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tempo.o tempo.cpp

release_central.o: release_central.cpp release_central.h \
		evento.h \
		tempo.h \
		central.h \
		mensagem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release_central.o release_central.cpp

estatisticas.o: estatisticas.cpp estatisticas.h \
		tempo.h \
		mensagem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o estatisticas.o estatisticas.cpp

moc_Mainwindow.o: moc_Mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Mainwindow.o moc_Mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

